export default [
	// OS
	".DS_Store",
	"Thumbs.db",

	// IDE
	".idea",
	"*.iml",
	".vscode",
	".vscode-test",
	"*.sublime-project",
	"*.sublime-workspace",

	// Logs
	"logs/**/*",
	"*.log",
	"npm-debug.log*",
	"yarn-debug.log*",
	"yarn-error.log*",
	"lerna-debug.log*",

	// Diagnostic reports (https://nodejs.org/api/report.html)
	"report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json",

	// Runtime data
	"pids",
	"*.pid",
	"*.seed",
	"*.pid.lock",

	// Directory for instrumented libs generated by jscoverage/JSCover
	"lib-cov/**/*",

	// Coverage directory used by tools like istanbul
	"coverage/**/*",
	"*.lcov",

	// nyc test coverage
	".nyc_output",

	// Compiled binary addons (https://nodejs.org/api/addons.html)
	"build/Release/**/*",

	// Dependencies
	"node_modules/**/*",

	// Optional REPL history
	".node_repl_history",

	// Generated code
	"dist/**/*",

	// Test
	"test/fixtures/**/*",
	"test/outputs/**/*",

	// Generated types
	"types/**/*",

	// Reports
	"reports/**/*",

	// Caches
	".cache/**/*",
	".eslintcache",
	".stylelintcache",
	".cspellcache",
	"*.tsbuildinfo",
];
